GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "event name",
  "description": "event description",
  "date": "2020-01-01T00:00:00",
  "price": 100
}